spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/mymall
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      format_sql: true

logging:
  level:
    org.hibernate.SQL: debug  # org.hibernate가 쏘는 SQL 문장들을 debug 레벨의 log로 출력.
